name: Lint

on:
  pull_request:
    types:
      - "opened"
      - "synchronize"
  push:
    branches:
      - "main"

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v7

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.10"
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install dependencies
        run: |
          uv sync --locked --dev

      - name: Ruff lint
        run: |
          uv run --no-sync ruff check --output-format=github .

      - name: Ruff format
        run: |
          uv run --no-sync ruff format --check --diff .

      - name: Type check
        run: |
          uv run --no-sync ty check
