name: Publish

on:
  workflow_dispatch:
  release:
    types: [ published ]

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v7

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.10"
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Build
        run: |
          uv build

      - name: Publish
        env:
          UV_PUBLISH_USERNAME: ${{ secrets.PYPI_USERNAME }}
          UV_PUBLISH_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          uv publish
